apiVersion: batch/v1
kind: Job
metadata:
  name: pinecone-data-loader
spec:
  template:
    spec:
      containers:
      - name: loader
        image: yashwanthydg/bot-service:v6
        command: ["python", "scripts/load_data.py"]
        env:
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: pinecone-credentials
              key: api_key
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        - name: AWS_REGION
          value: "us-east-1"   
      restartPolicy: Never
  backoffLimit: 4
