apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot-service
  template:
    metadata:
      labels:
        app: bot-service
    spec:
      containers:
      - name: bot-service
        image: yashwanthydg/bot-service:v2 # <-- IMPORTANT: Change this
        ports:
        - containerPort: 8001
        env:
        - name: AWS_REGION
          value: "us-east-1" # Or your preferred region
        # In a real cluster, you would use a secret for Pinecone credentials
        - name: PINECONE_API_KEY
          valueFrom:
            secretKeyRef:
              name: pinecone-credentials
              key: api_key
        # Ensure the pod's Service Account has an IAM role with permissions
        # to access Bedrock.
        envFrom:
        - secretRef:
            name: aws-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  type: ClusterIP # Only accessible within the cluster
  selector:
    app: bot-service
  ports:
  - port: 8001
    targetPort: 8001
